services:
  app:
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - STRING_SESSION=${STRING_SESSION}
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - PROXY=${PROXY:-}
    volumes:
      - downloads:/app/downloads

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - redis-data:/data

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
  downloads:
    driver: local