services:
  app:
    container_name: telegram-bot
    restart: unless-stopped
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
    env_file:
      - stack.env
    volumes:
      - ./downloads:/app/downloads
      - .env:/app/.env

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local