services:
  app:
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./downloads:/app/downloads
      - .env:/app/.env

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - redis-data:/data

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local